### ISSUE TITLE
license / original code?

### ISSUE THREAD

**Issue by Sciss** [Debapriya-Tula/Speech_Dereverberation#1]
Hello. I noticed that wpe.py is literally the same as [here](https://github.com/helianvine/fdndlp/blob/master/python/wpe.py), with the latter indicating the author being Teng Xiang. Could you clarify if you copied the source code or if you are the original author? In the former case, I suppose you should add the license information which seems to be MIT. Thank you.

**Comment by Debapriya-Tula** [comment]
Thank you for pointing that out. This indeed is the code you referred to, with minor modifications to it. I added the license.
